Fix this warning: 

 FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  mask_x[[x_ind]], mask_y[[y_ind]] = True, True
  

In [20]:
import numpy as np

# incoming messages, if not overlapping are added at the beginning of the list
# if a message overlaps, its popularity is updated (+=new popularity), and age is reset to 0
messages = np.array([3, 1, 2, 4])
no_shares = [1, 1, 3, 1]
ages = [1, 1, 1, 1]

target_feed = (messages, no_shares, ages)
incoming_ids = np.array([100, 2])
incoming_shares = np.array([10, 4])

print(f"incoming ids : {incoming_ids} --> feed: {messages}")
print(f"no_shares : {incoming_shares} --> feed: {no_shares}")
print(f"incoming age : {np.zeros(len(incoming_ids))} --> feed: {ages}")

incoming ids : [100   2] --> feed: [3 1 2 4]
no_shares : [10  4] --> feed: [1, 1, 3, 1]
incoming age : [0. 0.] --> feed: [1, 1, 1, 1]


In [22]:
verbose = True
messages, no_shares, ages = [np.array(i) for i in target_feed]
# return sorted intersection
overlap, x_ind, y_ind = np.intersect1d(messages, incoming_ids, return_indices=True)
# print(new_messages, new_shares, new_ages)
if verbose:
    print(f"incoming ids : {incoming_ids} --> feed: {messages}")
    print(f"no_shares : {incoming_shares} --> feed: {no_shares}")
    print(f"incoming age : {np.zeros(len(incoming_ids))} --> feed: {ages}")

    print(f"overlap message between {messages} and {incoming_ids} are: {overlap}")
    print("update no_share and age of overlapping messages.. ")
    print(f"before:  messages: {messages}, shares: {no_shares}, ages: {ages}")

print("incoming except for overlap: ", incoming_ids[~np.array(y_ind)])
print("incoming except for overlap (tuple): ", incoming_ids[tuple(~np.array(y_ind))])
print("x_ind, y_ind: ", x_ind, y_ind)
# mask_y = np.zeros(len(incoming_ids), bool)
# mask_y[[y_ind]] = True

# print("(correct) incoming except for overlap: ", incoming_ids[~mask_y])
# mask_x = np.zeros(len(messages), bool)
# mask_x[[x_ind]] = True

mask_x, mask_y = np.zeros(len(messages), bool), np.zeros(len(incoming_ids), bool)
print("mask_x:", mask_x)
print("mask_y:", mask_y)
mask_x[x_ind], mask_y[y_ind] = True, True  # changed mask_x[[x_ind]] to mask_x[x_ind]

incoming ids : [100   2] --> feed: [3 1 2 4]
no_shares : [10  4] --> feed: [1 1 3 1]
incoming age : [0. 0.] --> feed: [1 1 1 1]
overlap message between [3 1 2 4] and [100   2] are: [2]
update no_share and age of overlapping messages.. 
before:  messages: [3 1 2 4], shares: [1 1 3 1], ages: [1 1 1 1]
incoming except for overlap:  [100]
incoming except for overlap (tuple):  100
x_ind, y_ind:  [2] [1]
mask_x: [False False False False]
mask_y: [False False]


In [18]:
mask_x, mask_y

(array([False, False,  True, False]), array([False,  True]))

In [12]:
type(x_ind)

numpy.ndarray

In [8]:
mask_x, mask_y

(array([False, False,  True, False]), array([False,  True]))

In [15]:
mask_x[x_ind] = True

In [16]:
mask_x

array([False, False,  True, False])