## Tracking message info 

In [16]:
import numpy as np

messages = np.array([1, 2, 3])
ages = np.array([1, 5, 0])
noshares = np.array([1, 1, 1])

In [21]:
info

array([[1, 2, 3],
       [1, 0, 0],
       [1, 1, 1]])

In [25]:
info[0]

array([1., 2., 3.])

In [22]:
info = np.vstack([info, np.zeros(len(messages))])

In [23]:
info

array([[1., 2., 3.],
       [1., 0., 0.],
       [1., 1., 1.],
       [0., 0., 0.]])

In [26]:
c = np.array([[1.0, 2.0, 3.0], [1.0, 0.0, 0.0], [1.0, 1.0, 1.0], [0.0, 0.0, 0.0]])

In [28]:
a = np.hstack([info, c])

In [29]:
a

array([[1., 2., 3., 1., 2., 3.],
       [1., 0., 0., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [30]:
a.shape

(4, 6)

In [31]:
a[0]

array([1., 2., 3., 1., 2., 3.])

In [11]:
info = np.vstack([messages, ages, noshares])

In [14]:
a = info[:, 2]
a

array([3, 0, 1])

In [6]:
np.where(messages == 1)  # result is a tuple with all row idxs, all columns idxs

(array([0]),)

In [20]:
ages[np.where(messages == 3)] = 100
ages

array([  1,   5, 100])

In [ ]:
mask = 

In [8]:
(idx,) = np.where(messages == 1)[0]

In [9]:
idx

0

## Chunking groups of users

In [1]:
import igraph as ig
import numpy as np

In [2]:
net = ig.Graph.Read_GML("experiments/10252023_v3.3_small/data/network_20.gml")
net.summary()

'IGRAPH D--- 1051 30671 -- \n+ attr: bot (v), id (v), misinfo (v), party (v), uid (v)'

In [3]:
nodes = [i for i in net.vs]

In [6]:
order = np.random.permutation(range(len(nodes)))
order[:10]

array([420, 648, 881, 802, 872, 529, 820, 637, 561, 189])

In [7]:
def chunks(lst, n):
    """Yield successive n-sized chunks from lst."""
    for i in range(0, len(lst), n):
        yield lst[i : i + n]

In [17]:
groups = chunks(order, len(nodes) // 3)

In [21]:
len(nodes) / 10

105.1

In [18]:
for i in groups:
    # print(i)
    print(len(i))

350
350
350
1


In [4]:
nodes[:10]

[igraph.Vertex(<igraph.Graph object at 0x11f073240>, 0, {'id': 0.0, 'party': -0.255325490196078, 'misinfo': 0.117647058823529, 'bot': 0.0, 'uid': '61445'}),
 igraph.Vertex(<igraph.Graph object at 0x11f073240>, 1, {'id': 1.0, 'party': -0.231594117647059, 'misinfo': 0.0980392156862745, 'bot': 0.0, 'uid': '98847'}),
 igraph.Vertex(<igraph.Graph object at 0x11f073240>, 2, {'id': 2.0, 'party': -0.0367808219178082, 'misinfo': 0.116438356164383, 'bot': 0.0, 'uid': '99106'}),
 igraph.Vertex(<igraph.Graph object at 0x11f073240>, 3, {'id': 3.0, 'party': 0.158832692307692, 'misinfo': 0.269230769230769, 'bot': 0.0, 'uid': '33605'}),
 igraph.Vertex(<igraph.Graph object at 0x11f073240>, 4, {'id': 4.0, 'party': -0.150746511627907, 'misinfo': 0.151162790697674, 'bot': 0.0, 'uid': '120848'}),
 igraph.Vertex(<igraph.Graph object at 0x11f073240>, 5, {'id': 5.0, 'party': -0.168448, 'misinfo': 0.24, 'bot': 0.0, 'uid': '98468'}),
 igraph.Vertex(<igraph.Graph object at 0x11f073240>, 6, {'id': 6.0, 'party': -

In [32]:
import numpy as np

engagement = np.array([0.3, 0.2, 0.1])
popularity = np.array([1, 1, 1])
ages = np.array([2, 5, 2])
recency = np.exp(-0.4 * (ages**0.4))

In [33]:
recency

array([0.58989946, 0.4669834 , 0.58989946])

In [34]:
w_e = 1 / 3
w_p = 1 / 3

In [35]:
np.sum([w_e * engagement, w_p * popularity], axis=0)

array([0.43333333, 0.4       , 0.36666667])

In [37]:
ranking = np.sum([w_e * engagement, w_p * popularity], axis=0) * [0.5, 1, 1]
ranking

array([0.21666667, 0.4       , 0.36666667])

In [14]:
np.array([2, 2, 3]) * np.array([0.5, 1, 1])

array([1., 2., 3.])

In [20]:
!pwd

/Users/baott/SimSoM/small_net_exps


In [21]:
import glob
import os

print(f"current dir: {os.getcwd()}")
os.chdir("small_net_exps")

fpaths = glob.glob("sbatch30/*.sh")
fpaths

current dir: /Users/baott/SimSoM/small_net_exps


FileNotFoundError: [Errno 2] No such file or directory: 'small_net_exps'

In [ ]:
workflow / sbatch_40 / test.sh